Repository stashapp/CommunityScripts, pull requests merged in 2022-12, with the labels that each got.

#113 [renamerOnUpdate] fix bug
  plugins/renamerOnUpdate/renamerOnUpdate.py
  plugins/renamerOnUpdate/renamerOnUpdate.yml
Labels: bug

#118 [renamerOnUpdate] fix field_whitespaceSeperator
  plugins/renamerOnUpdate/renamerOnUpdate.py
  plugins/renamerOnUpdate/renamerOnUpdate.yml
Labels: bug

#107 [renamerOnUpdate] changed the rename method
  plugins/renamerOnUpdate/renamerOnUpdate.py
  plugins/renamerOnUpdate/renamerOnUpdate.yml
Labels: enhancement

#99 Gallery DateParser - Parse dates from filenames & path for galleries
  plugins/DateParser/date_parser.py
  plugins/DateParser/date_parser.yml
  plugins/DateParser/requirements.txt
Labels: plugin

#120 [renamerOnUpdate] adding back reduce path option
  plugins/renamerOnUpdate/README.md
  plugins/renamerOnUpdate/renamerOnUpdate.py
  plugins/renamerOnUpdate/renamerOnUpdate.yml
Labels: enhancement
