Repository stashapp/CommunityScripts, pull requests merged in 2022-03, with the labels that each got.

#41 [renamerOnUpdate] Search recursively for parent studio template
  plugins/renamerOnUpdate/renamerOnUpdate.py
  plugins/renamerOnUpdate/renamerOnUpdate.yml
Labels: bug, enhancement

#42 Lots of Collection/Genres updates for Plex agent
  3rd party/StashPlexAgent.bundle/Contents/Code/__init__.py
  3rd party/StashPlexAgent.bundle/Contents/DefaultPrefs.json
  3rd party/StashPlexAgent.bundle/README.md
Labels: enhancement

#43 [renamer] Enforce utf-8 encoding when opening FILE_DRYRUN_RESULT
  plugins/renamer/renamerTask.py
Labels: bug
